### ISSUE TITLE
Choose Lines and directions

### ISSUE THREAD

**Issue by daknoblo** [skastenholz/MMM-DVB#1]
Hello,

first of all, thank you for this module !

It would be great if you can choose/filter the Line and / or direction in the module.

In my case, the starting point is Postplatz, from there are starting many Lines which i'm not interested in.

BR Daniel

btw, this is my first issue on github

**Comment by skastenholz** [comment]
Hi Daniel,

thank you for your feedback. I added the functionality to filter lines. Please have a try.

Regarding destinations I am wondering what is exactly on your mind and how it relates to the line filtering. Could you please elaborate and provide an example config file? Thank you!

Stefan

**Comment by daknoblo** [comment]
Hello Stefan,

Filter is working good.

With the direction i mean the 2 different directions of one line. For example Line 8 have two different directions to Südvorstadt and Hellerau. But im only interestet in one direction because it's my line to the office.

Sample confid would be:

`config: {
      stopName: 'Hauptbahnhof', // Which stop would you like to have displayed?
      timeOffset: 5,  // With how many minutes in advance should connections be displayed?
      resultNum: 5, // How many connections should be displayed?
      lines: ["4", "8"], // What lines should be displayed?
      direction: ["Striesen","Südvorstadt"], // What direction depending of selected line should be displayed?
      reload: 60000 // How often should the information be updated? (In milliseconds)
    }`

I hope this is much clearer.

Daniel
