### ISSUE TITLE
dvb.findStop not a function

### ISSUE THREAD

**Issue by Am4rantheus** [skastenholz/MMM-DVB#11]
Hi, 

unfortunatly out of the sudden the MMM-DVB module is not showing any data anymore.
With `pm2 logs` Ive stumbled across the following error: 

`0|MagicMir | [03.05.2023 22:17.22.497] [ERROR] Whoops! There was an uncaught exception...
0|MagicMir | [03.05.2023 22:17.22.501] [ERROR] TypeError: dvb.findStop is not a function
0|MagicMir |     at Class.findStop (/home/pi/MagicMirror/modules/MMM-DVB/node_helper.js:24:13)
0|MagicMir |     at Class.socketNotificationReceived (/home/pi/MagicMirror/modules/MMM-DVB/node_helper.js:44:26)
0|MagicMir |     at Socket.<anonymous> (/home/pi/MagicMirror/js/node_helper.js:108:11)
0|MagicMir |     at Socket.emit (node:events:513:28)
0|MagicMir |     at Socket.emitUntyped (/home/pi/MagicMirror/node_modules/socket.io/dist/typed-events.js:69:22)
0|MagicMir |     at /home/pi/MagicMirror/node_modules/socket.io/dist/socket.js:703:39
0|MagicMir |     at process.processTicksAndRejections (node:internal/process/task_queues:78:11)
`

Any idea how to fix that?

**Comment by skastenholz** [comment]
Hi, 

same for me. It seems to me that currently the underlying API service for querying DVB data is down or has changed (https://webapi.vvo-online.de/). Unfortunately, I cannot find any official announcement nor an updated API client library (https://github.com/offenesdresden/dvbjs). 

Therefore, there is nothing we can do about it (as far as I know) at the moment.

**Comment by skastenholz** [comment]
The root cause is identified in https://github.com/offenesdresden/dvbjs/issues/104. Once a fixed dvbjs library is released I can also update this module.

**Comment by Am4rantheus** [comment]
> The root cause is identified in [offenesdresden/dvbjs#104](https://github.com/offenesdresden/dvbjs/issues/104). Once a fixed dvbjs library is released I can also update this module.

Thx for the work. I wanted to be badass today for a party and show people the lines in the area for planning their home journey. Well shit happens.

**Comment by skastenholz** [comment]
Well, just got the idea to temporarily fix it by overriding the axios version. Please verify if it works for you as well.

**Comment by Am4rantheus** [comment]
Could you explain that a bit more? Im not that deep into IT to get what you want. Do I just need to update axios?

**Comment by skastenholz** [comment]
Alright, please just follow a guide like https://bensworld.net/homelab/how-to-update-your-magic-mirror-modules/ in order to update MagicMirror modules :-)
