### ISSUE TITLE
No Data

### ISSUE THREAD

**Issue by ostfilinchen** [skastenholz/MMM-DVB#2]
Hello,

i have installed the module but i get no data. The result is "Keine Verbindungen".

The config i set like in the readme. Can u please check this.

PS: My rpi is up to date and also the MM.

Regards
Daniel

**Comment by daknoblo** [comment]
Please paste your configuration.

**Comment by ostfilinchen** [comment]
So here is the log from npm install:
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN prefer global jshint@2.9.5 should be installed with -g
MMM-DVB@0.0.1 E:\MagicMirror\modules\MMM-DVB
+-- dvbjs@4.3.5
| +-- proj4@2.4.4
| | +-- mgrs@1.0.0
| | `-- wkt-parser@1.2.0
| +-- request@2.81.0
| | +-- aws-sign2@0.6.0
| | +-- aws4@1.6.0
| | +-- caseless@0.12.0
| | +-- combined-stream@1.0.5
| | | `-- delayed-stream@1.0.0
| | +-- extend@3.0.1
| | +-- forever-agent@0.6.1
| | +-- form-data@2.1.4
| | | `-- asynckit@0.4.0
| | +-- har-validator@4.2.1
| | | +-- ajv@4.11.8
| | | | +-- co@4.6.0
| | | | `-- json-stable-stringify@1.0.1
| | | |   `-- jsonify@0.0.0
| | | `-- har-schema@1.0.5
| | +-- hawk@3.1.3
| | | +-- boom@2.10.1
| | | +-- cryptiles@2.0.5
| | | +-- hoek@2.16.3
| | | `-- sntp@1.0.9
| | +-- http-signature@1.1.1
| | | +-- assert-plus@0.2.0
| | | +-- jsprim@1.4.1
| | | | +-- assert-plus@1.0.0
| | | | +-- extsprintf@1.3.0
| | | | +-- json-schema@0.2.3
| | | | `-- verror@1.10.0
| | | |   `-- assert-plus@1.0.0
| | | `-- sshpk@1.13.1
| | |   +-- asn1@0.2.3
| | |   +-- assert-plus@1.0.0
| | |   +-- bcrypt-pbkdf@1.0.1
| | |   +-- dashdash@1.14.1
| | |   | `-- assert-plus@1.0.0
| | |   +-- ecc-jsbn@0.1.1
| | |   +-- getpass@0.1.7
| | |   | `-- assert-plus@1.0.0
| | |   +-- jsbn@0.1.1
| | |   `-- tweetnacl@0.14.5
| | +-- is-typedarray@1.0.0
| | +-- isstream@0.1.2
| | +-- json-stringify-safe@5.0.1
| | +-- mime-types@2.1.16
| | | `-- mime-db@1.29.0
| | +-- oauth-sign@0.8.2
| | +-- performance-now@0.2.0
| | +-- qs@6.4.0
| | +-- safe-buffer@5.1.1
| | +-- stringstream@0.0.5
| | +-- tough-cookie@2.3.2
| | | `-- punycode@1.4.1
| | +-- tunnel-agent@0.6.0
| | `-- uuid@3.1.0
| `-- request-promise@4.2.1
|   +-- bluebird@3.5.0
|   +-- request-promise-core@1.1.1
|   `-- stealthy-require@1.1.1
+-- grunt@0.4.5
| +-- async@0.1.22
| +-- coffee-script@1.3.3
| +-- colors@0.6.2
| +-- dateformat@1.0.2-1.2.3
| +-- eventemitter2@0.4.14
| +-- exit@0.1.2
| +-- findup-sync@0.1.3
| | +-- glob@3.2.11
| | | +-- inherits@2.0.3
| | | `-- minimatch@0.3.0
| | `-- lodash@2.4.2
| +-- getobject@0.1.0
| +-- glob@3.1.21
| | +-- graceful-fs@1.2.3
| | `-- inherits@1.0.2
| +-- grunt-legacy-log@0.1.3
| | +-- grunt-legacy-log-utils@0.1.1
| | | +-- lodash@2.4.2
| | | `-- underscore.string@2.3.3
| | +-- lodash@2.4.2
| | `-- underscore.string@2.3.3
| +-- grunt-legacy-util@0.2.0
| | `-- lodash@0.9.2
| +-- hooker@0.2.3
| +-- iconv-lite@0.2.11
| +-- js-yaml@2.0.5
| | +-- argparse@0.1.16
| | | +-- underscore@1.7.0
| | | `-- underscore.string@2.4.0
| | `-- esprima@1.0.4
| +-- lodash@0.9.2
| +-- minimatch@0.2.14
| | +-- lru-cache@2.7.3
| | `-- sigmund@1.0.1
| +-- nopt@1.0.10
| | `-- abbrev@1.1.0
| +-- rimraf@2.2.8
| +-- underscore.string@2.2.1
| `-- which@1.0.9
+-- grunt-cli@1.2.0
| +-- findup-sync@0.3.0
| | `-- glob@5.0.15
| |   +-- inflight@1.0.6
| |   | `-- wrappy@1.0.2
| |   +-- minimatch@3.0.4
| |   +-- once@1.4.0
| |   `-- path-is-absolute@1.0.1
| +-- grunt-known-options@1.1.0
| +-- nopt@3.0.6
| `-- resolve@1.1.7
+-- grunt-contrib-csslint@2.0.0
| +-- chalk@1.1.3
| | +-- ansi-styles@2.2.1
| | +-- escape-string-regexp@1.0.5
| | +-- has-ansi@2.0.0
| | | `-- ansi-regex@2.1.1
| | +-- strip-ansi@3.0.1
| | `-- supports-color@2.0.0
| +-- csslint@1.0.5
| | +-- clone@2.1.1
| | `-- parserlib@1.1.1
| +-- lodash@4.17.4
| `-- strip-json-comments@2.0.1
+-- grunt-contrib-jshint@1.1.0
| `-- jshint@2.9.5
|   +-- cli@1.0.1
|   | `-- glob@7.1.2
|   |   +-- fs.realpath@1.0.0
|   |   `-- minimatch@3.0.4
|   +-- console-browserify@1.1.0
|   | `-- date-now@0.1.4
|   +-- htmlparser2@3.8.3
|   | +-- domelementtype@1.3.0
|   | +-- domhandler@2.3.0
|   | +-- domutils@1.5.1
|   | | `-- dom-serializer@0.1.0
|   | |   +-- domelementtype@1.1.3
|   | |   `-- entities@1.1.1
|   | +-- entities@1.0.0
|   | `-- readable-stream@1.1.14
|   |   +-- core-util-is@1.0.2
|   |   +-- isarray@0.0.1
|   |   `-- string_decoder@0.10.31
|   +-- lodash@3.7.0
|   +-- minimatch@3.0.4
|   | `-- brace-expansion@1.1.8
|   |   +-- balanced-match@1.0.0
|   |   `-- concat-map@0.0.1
|   +-- shelljs@0.3.0
|   `-- strip-json-comments@1.0.4
+-- grunt-cssbeautifier@0.1.2
| `-- cssbeautify@0.3.1
+-- grunt-jsbeautifier@0.2.13
| +-- async@2.5.0
| +-- js-beautify@1.6.14
| | +-- config-chain@1.1.11
| | | `-- proto-list@1.2.4
| | +-- editorconfig@0.13.3
| | | +-- commander@2.11.0
| | | `-- lru-cache@3.2.0
| | |   `-- pseudomap@1.0.2
| | +-- mkdirp@0.5.1
| | | `-- minimist@0.0.8
| | `-- nopt@3.0.6
| +-- rc@1.2.1
| | +-- deep-extend@0.4.2
| | +-- ini@1.3.4
| | `-- minimist@1.2.0
| +-- semver@5.4.1
| `-- underscore.string@3.3.4
|   +-- sprintf-js@1.1.1
|   `-- util-deprecate@1.0.2
+-- grunt-markdownlint@1.0.41
| `-- markdownlint@0.6.0
|   `-- markdown-it@8.3.2
|     +-- argparse@1.0.9
|     | `-- sprintf-js@1.0.3
|     +-- entities@1.1.1
|     +-- linkify-it@2.0.3
|     +-- mdurl@1.0.1
|     `-- uc.micro@1.0.3
`-- time-grunt@1.4.0
  +-- date-time@1.1.0
  | `-- time-zone@0.1.0
  +-- figures@1.7.0
  | `-- object-assign@4.1.1
  +-- number-is-nan@1.0.1
  +-- pretty-ms@2.1.0
  | +-- is-finite@1.0.2
  | +-- parse-ms@1.0.1
  | `-- plur@1.0.0
  `-- text-table@0.2.0

And here is my config:
		{
           module: 'MMM-DVB',
           position: 'top_left',
           config: {
              stopName: "Hauptbahnhof", // Which stop would you like to have displayed?
              timeOffset: 5,  // With how many minutes in advance should connections be displayed?
              resultNum: 5, // How many connections should be displayed?
              //lines: ["1", "2"], // What lines should be displayed?
              //directions: ["Striesen"], // What directions should be displayed?
              reload: 60000 // How often should the information be updated? (In milliseconds)
                    }
        },

**Comment by daknoblo** [comment]
Config looks good, but i think the problem is that there is no direct connect from Hauptbahnhof to direction Striesen with Line 1 or 2. These lines are starting from Pirnaischer Platz to Striesen, so you have to choose a Line which is travelling from Hauptbahnhof to Pirnaischer Platz and then change to Line 1 or 2.

Maybe you can try Line 10 from Hauptbahnhof to Striesen or Bus 61.

**Comment by ostfilinchen** [comment]
no. same result

		{
           module: 'MMM-DVB',
           position: 'top_left',
           config: {
              stopName: "Hauptbahnhof", // Which stop would you like to have displayed?
              timeOffset: 5,  // With how many minutes in advance should connections be displayed?
              resultNum: 5, // How many connections should be displayed?
              lines: ["10", "61"], // What lines should be displayed?
              //directions: ["Striesen"], // What directions should be displayed?
              reload: 60000 // How often should the information be updated? (In milliseconds)
                    }
        }

also with 

		{
           module: 'MMM-DVB',
           position: 'top_left',
           config: {
              stopName: "Hauptbahnhof", // Which stop would you like to have displayed?
              timeOffset: 5,  // With how many minutes in advance should connections be displayed?
              resultNum: 5, // How many connections should be displayed?
              lines: ["10", "61"], // What lines should be displayed?
              directions: ["Striesen"], // What directions should be displayed?
              reload: 60000 // How often should the information be updated? (In milliseconds)
                    }
        }

**Comment by daknoblo** [comment]
Do you get any results if you leave Directions empty and choose a well frequented line (7, 8, 10) ?

**Comment by ostfilinchen** [comment]
no data...

this is what i get in dev-mode (MMM-DVB.js Line 162):
Response: {"id":"module_5_MMM-DVB","connections":[]}

and this the request of line 156:
Request: {"id":"module_5_MMM-DVB","stopName":"Hauptbahnhof","timeOffset":5,"resultNum":5,"lines":[],"directions":[]}

**Comment by skastenholz** [comment]
Hi Daniel,

can you please try to disable the "lines" and "directions" options completely:

```
{
   module: 'MMM-DVB',
   position: 'top_left',
   config: {
      stopName: 'Hauptbahnhof',
      timeOffset: 5,
      resultNum: 5,
      reload: 60000
   }
}
```
Best regards,
Stefan

**Comment by ostfilinchen** [comment]
Hi Stefan,

no, same result: "Keine Verbindungen verfügbar".

Best regards,
Daniel

2017-10-31 22:32 GMT+01:00 Stefan Kastenholz <notifications@github.com>:

**Comment by skastenholz** [comment]
Hi Daniel,

I suggest the following steps:
1) Can you please install the https://github.com/yo-less/MMM-KVV module for testing purposes. I would like to verify if the issue is module-specific.
2) Can you please share your magic mirror installation folder? I would like to verify if the issue is related to the Magic Mirror setup.

Thank you!

Best regards,
Stefan

**Comment by ostfilinchen** [comment]
Hi Stefan,

for testing purposes I have installed the MMM-KVV. This module works for me.

Which folder need you in the MagicMirror installation?

Regards
Daniel

Am 04.11.2017 16:53 schrieb "Stefan Kastenholz" <notifications@github.com>:

Hi Daniel,

I suggest the following steps:

   1. Can you please install the https://github.com/yo-less/MMM-KVV module
   for testing purposes. I would like to verify if the issue is
   module-specific.
   2. Can you please share your magic mirror installation folder? I would
   like to verify if the issue is related to the Magic Mirror setup.

Thank you!

Best regards,
Stefan

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/skastenholz/MMM-DVB/issues/2#issuecomment-341907665>,
or mute the thread

**Comment by ostfilinchen** [comment]
Hi... me again,

after I installed the MMM-KVV and reinstall your module - it works.

Looks that anything missing in your installationscript.

Regards
Daniel

Am 16.11.2017 18:17 schrieb "Mr. Filinchen" <ostfilinchen@gmail.com>:

**Comment by skastenholz** [comment]
Hi Daniel,

before I answered you 14 days ago I setup a fresh MM installation and installed MMM-DVB only. Therefore, I cannot reconstruct your situation.

Best regards,
Stefan

**Comment by ChrissisCorner** [comment]
Hello,
I downloaded and installed it aswell. But it doesn't even display on the screen. The rest is working fine and I can't figure out what it is. Any ideas?

**Comment by skastenholz** [comment]
Hi Chrissi,

it seems like there was an API change in a downstream dependency. Can you please checkout the latest code and re-evaluate? Thanks.

Best regards,
Stefan

**Comment by ChrissisCorner** [comment]
Hello Stefan,

I tried again and still can't get it to work.
