### ISSUE TITLE
Different stations

### ISSUE THREAD

**Issue by musiat** [skastenholz/MMM-DVB#5]
Hi,
using your module for a while and it is the main reason for woman acceptance for always-on-display ;o)
Question/Issue: Family members are leaving house in different directions for school/work and use different stations. (How) is it possible to use multiple instances of MMM-DVB (e.g. on different MagicMirror-pages).
Thanks in advance
Marko

**Comment by kolewu** [comment]
Just use two instances of the module like so
```javascript
	{
	    module: 'MMM-DVB',
	    position: 'top_right',
	    config: {
		stopName: 'station1',
		timeOffset: 3,
		resultNum: 9,
		noTableHeader: true
	    }
	},
	{
	    module: 'MMM-DVB',
	    position: 'top_right',
	    config: {
		stopName: 'station2',
		timeOffset: 3,
		resultNum: 5,
		noTableHeader: true
	    }
	},
```
I use this as a home dashboard with a 7" screen and in order to save space on the screen I remove the table header.

**Comment by musiat** [comment]
Thank you very much - this just works.
Thought it would be more complicated..
Suggestion: putting this issue with solution into readme
